### ISSUE TITLE
keyring add needs restart

### ISSUE THREAD

**Issue by adur1990** [servalproject/serval-dna#126]
After I add my first sid with keyring add serval has to be restarted. Otherwise, neither id self nor the rest api will return the generated sid.

**Comment by lakeman** [comment]
Correct, unless you use the restful keyring api that is.

**Comment by quixotique** [comment]
The CLI interface needs to be changed to act as a REST API client if the daemon is running, otherwise fall back to acting directly on the keyring/database if not (with suitable file locks to avoid race conditions if the daemon is starting).  That is a non-trivial architectural change with no allocated budget at the moment, so for the time being while the server is running you must use the RESTful API to make keyring changes.  Fortunately it is well documented.
