### ISSUE TITLE
Test FileTransferUnreliableBigMDP sometimes fails

### ISSUE THREAD

**Issue by rom1v** [servalproject/serval-dna#67]
`tests/rhizomeprotocol` number 8 sometimes fails (but not always): _Big new bundle over unreliable MDP transport_

Here is the log:
https://gist.github.com/rom1v/6038722

**Comment by lakeman** [comment]
I added the test because we saw MDP transfers stalling over packet radio links (mesh extenders...). We need to improve the protocol to pipeline requests for more data instead of relying on packet retransmissions.

For now we should probably reduce the file size for this test so we don't have to wait as long for the transfer to complete.

**Comment by lakeman** [comment]
This test allows 2 minutes for the transfer to complete, (see e6ce14af) but in the development branch usually completes in around 10 seconds.
